# Generated by Django 6.0.3 on 2026-03-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='default title', max_length=50),
            preserve_default=False,
        ),
    ]
